# Application
base.url=http://devui.appsavy.com/
login.url=http://devui.appsavy.com/

# Browser & Execution
browser=chromium
headless=false
slowmo=2000

# Default / fallback credentials
default.username=9155208902
default.password=123456
username=9155208902
password=123456